### PR TITLE
small fixes to weeds 3d table and all MUI tables are now reactive

### PR DESCRIPTION
**Pull request by azeng4499**
- reordered elements in Weeds 3d table
- changed all file size numbers to MB with units (should sizes over 1000 MB be changed to KB?)
- added window size listeners to all Material tables so they change according to screen size and stay constant

### CODE REVIEW

**Comment by brianwdavis** [comment]
I think there used to be an event listener and resizing the window made the application crash because of infinite rerendering, so that's worth testing.

**Comment by azeng4499** [comment]
> I think there used to be an event listener and resizing the window made the application crash because of infinite rerendering, so that's worth testing.

I think the empty dependency array at the end of the useEffect prevents infinite re-rendering, I tested this by adding a console.log() inside the useEffect. Seems like it's only running when the user is actively resizing the page so it shouldn't crash the application. Let me know if I'm missing something though.

**Comment by mikahpinegar** [comment]
there's a conflict that needs to be resolved

**Comment by azeng4499** [comment]
> there's a conflict that needs to be resolved

conflicts should be resolved

**Comment by mikahpinegar** [comment]
biomass farm values still has a double scrollbar

**Comment by mikahpinegar** [comment]
everything else looks good though, once that's taken care of i'll merge into dev

**Review by mikahpinegar — APPROVED** [review]

**Pull request merged**
