### PR TITLE
RBAC for devices

### LINKED ISSUE #50: urls for dev and master
Send slack message with url for dev and master branches to data flow team.  Might be good showcase of demonstrating best practices in terms of making changes on dev branch first and testing before merging with master.  New concept for some of the scientists on the team.  Please also check my settings on github to see if those should be our recommend settings on repositories

### LINKED ISSUE #52: Step 1: partial parse of hologram data
Replace the use of Slack as a system of status checking sensors. It can look like the current info displayed in the "barc-test" channel on slack.  The goal is to replace the slack channel notification and test.  We do not want to use slack in future iterations for this task.

Match state "tag" to access control.  Keep current "devices" view on dashboard the same with green, white and red.  Note using the Hologram API for everything except access permission which is stored in MySQL

### LINKED ISSUE #60: Information for Parsing the Hologram String
The order of the data string for Gateways and Nodes: 
https://docs.google.com/spreadsheets/d/1uwCadZ4SFWu45WO2qcbT7PEGb24SruGUUx_kUoRhSV0/edit#gid=0

### PR DESCRIPTION
**Pull request by rbandooni**
Fixes #50, Fixes #52 , and  Fixes #60 

Preview at [Dev Site](https://dev.precisionsustainableag.ml)

### CODE REVIEW

**Comment by screberg** [comment]
This says draft pull request.  Does that mean you want feedback or are working on the pull request still?  I'm still learning...

**Comment by rbandooni** [comment]
Fixed an issue where hologram server was returning a CORS error for certain URLs

**Comment by rbandooni** [comment]
Hologram has changed their device-specific API and is no longer returning lat long for devices, so map feature has been disabled in this pull request. Future pull requests can tackle this based on suggestions.

**Comment by rbandooni** [comment]
@screberg The latest commit resolves #69 . It is live at the dev URL

**Pull request merged**
